[versions]
freefair = "9.0.0"
commons-collections4 = "4.5.0"
telegrambots = "9.0.0"

[plugins]
freefair-aggregate-javadoc = { id = "io.freefair.aggregate-javadoc", version.ref = "freefair" }
freefair-lombok = { id = "io.freefair.lombok", version.ref = "freefair" }

[libraries]
commons-collections4 = { module = "org.apache.commons:commons-collections4", version.ref = "commons-collections4" }
telegrambots-client = { module = "org.telegram:telegrambots-client", version.ref = "telegrambots" }
telegrambots-spring-boot-starter = { module = "org.telegram:telegrambots-springboot-longpolling-starter", version.ref = "telegrambots" }

[bundles]
telegrambots = ["telegrambots-client", "telegrambots-spring-boot-starter"]
